{{- if .Values.routers.enabled }}
{{- range .Values.routers.devices }}
{{- if .ip }}
---
# Service for device monitoring (works with both DNS names and IP addresses)
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- with .ports }}
  ports:
  {{- range . }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
    {{- with .protocol }}
    protocol: {{ . }}
    {{- end }}
  {{- end }}
  {{- else }}
  # Default ports for common network device services
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  {{- end }}
  selector: {}

---
# Endpoint for device monitoring (works with both DNS names and IP addresses)
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subsets:
- addresses:
  - ip: {{ .ip }}
  {{- with .ports }}
  ports:
  {{- range . }}
  - name: {{ .name }}
    port: {{ .port }}
    {{- with .protocol }}
    protocol: {{ . }}
    {{- else }}
    protocol: TCP
    {{- end }}
  {{- end }}
  {{- else }}
  # Default ports for common network device services
  ports:
  - name: https
    port: 443
    protocol: TCP
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
